name: Advanced Security Scanning

on:
  push:
    branches: [ "main", "develop" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday
  workflow_dispatch:  # Allow manual triggering

# Environment Configuration
env:
  # Core versions
  GO_VERSION: '^1.21'
  NODE_VERSION: '20.x'
  PYTHON_VERSION: '3.10'
  DOCKER_VERSION: '20.10'
  
  # Security settings
  SECURITY_LEVEL: 'high'  # Can be 'low', 'medium', 'high', or 'paranoid'
  FAIL_ON: 'high'  # Fail on vulnerabilities of this level or higher
  
  # Feature toggles
  ENABLE_CONTAINER_SCAN: true
  ENABLE_SECRET_SCANNING: true
  ENABLE_SBOM_GENERATION: true
  ENABLE_BPF_CHECKS: true
  ENABLE_DEPENDENCY_SCAN: true
  ENABLE_SAST: true
  ENABLE_DAST: false  # Dynamic Application Security Testing
  
  # Notification settings
  NOTIFY_ON: 'failure'  # 'always', 'failure', or 'never'
  
  # Advanced BPF settings
  BPF_VERIFICATION_LEVEL: 'strict'  # 'permissive', 'normal', 'strict'
  BPF_ALLOW_UNPRIVILEGED: 'false'
  
  # Path exclusions
  EXCLUDE_PATHS: |
    **/vendor/**
    **/test/**
    **/examples/**
    **/node_modules/**
    **/.git/**

# Job definitions
jobs:
  security-scan:
    name: Advanced Security Scan
    runs-on: ${{ matrix.platform }}
    
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        # Uncomment for multi-platform testing
        # platform: [ubuntu-latest, macos-latest]
        include:
          - platform: ubuntu-latest
            container: ubuntu:22.04
          # - platform: macos-latest
          #   container: ''
    
    # Service containers for additional security tools
    services:
      # Add ZAP Proxy for DAST if enabled
      zap:
        if: env.ENABLE_DAST == 'true'
        image: owasp/zap2docker-stable
        ports:
          - 8080:8080
        options: >-
          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    # Checkout with full history for accurate analysis
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: 'recursive'
    
    # Setup environment
    - name: Setup Environment
      run: |
        echo "SECURITY_SCAN_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
        echo "SCAN_ID=$(uuidgen | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        mkdir -p ./results/{bpf,dependencies,sast,containers,secrets,reports}
    
    # Setup programming languages
    - name: Setup Go
      if: contains(github.event.pull_request.labels.*.name, 'go') || contains(github.event.pull_request.labels.*.name, 'all')
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true
        cache: true
        cache-dependency-path: |
          **/go.sum
          **/go.mod
    
    - name: Setup Python
      if: contains(github.event.pull_request.labels.*.name, 'python') || contains(github.event.pull_request.labels.*.name, 'all')
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        cache-dependency-path: |
          **/requirements*.txt
          **/setup.py
          **/pyproject.toml
    
    - name: Setup Node.js
      if: contains(github.event.pull_request.labels.*.name, 'javascript') || contains(github.event.pull_request.labels.*.name, 'typescript') || contains(github.event.pull_request.labels.*.name, 'node') || contains(github.event.pull_request.labels.*.name, 'all')
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    # Install security tools
    - name: Install Security Tools
      run: |
        # System updates
        sudo apt-get update
        
        # Core tools
        sudo apt-get install -y --no-install-recommends \
          jq yq curl wget git unzip \
          gnupg2 ca-certificates \
          build-essential \
          software-properties-common
        
        # BPF tooling
        if [ "${{ env.ENABLE_BPF_CHECKS }}" = "true" ]; then
          echo "Installing BPF tooling..."
          sudo apt-get install -y --no-install-recommends \
            clang llvm \
            libelf-dev \
            libbpf-dev \
            bpftool \
            linux-tools-common \
            linux-tools-$(uname -r) \
            bpfcc-tools \
            libbpf-tools
        fi
        
        # Container security tools
        if [ "${{ env.ENABLE_CONTAINER_SCAN }}" = "true" ]; then
          echo "Installing container security tools..."
          sudo apt-get install -y --no-install-recommends \
            docker.io \
            podman \
            skopeo \
            buildah
          sudo usermod -aG docker $USER
        fi
        
        # Network security tools
        echo "Installing network security tools..."
        sudo apt-get install -y --no-install-recommends \
          nmap \
          netcat \
          tcpdump \
          openssl \
          gpg \
          net-tools \
          iproute2
        
        # Install Python security tools
        echo "Installing Python security tools..."
        python -m pip install --upgrade pip
        python -m pip install --no-cache-dir \
          bandit \
          safety \
          trivy \
          semgrep \
          checkov \
          git+https://github.com/awslabs/git-secrets.git \
          detect-secrets \
          pip-audit
        
        # Install Go security tools
        if command -v go &> /dev/null; then
          echo "Installing Go security tools..."
          export PATH="$PATH:$(go env GOPATH)/bin"
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install github.com/google/osv-scanner/cmd/osv-scanner@latest
          go install github.com/aquasecurity/trivy@latest
          go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        fi
        
        # Install Node.js security tools
        if command -v npm &> /dev/null; then
          echo "Installing Node.js security tools..."
          sudo npm install -g \
            npm-audit-ci-wrapper \
            snyk \
            depcheck \
            @snyk/protect
        fi
        
        # Install additional security tools
        echo "Installing additional security tools..."
        # Add any additional tools here
    
    # Run security scans in parallel
    - name: Run Security Scans
      run: |
        # This is a placeholder for parallel scan execution
        # Each scan should be run in the background with proper error handling
        echo "Running security scans..."
        
        # Run scans in parallel using background processes
        (
          # SAST Scans
          if [ "${{ env.ENABLE_SAST }}" = "true" ]; then
            echo "Running SAST scans..."
            # Add SAST tools here
          fi
          
          # Dependency Scans
          if [ "${{ env.ENABLE_DEPENDENCY_SCAN }}" = "true" ]; then
            echo "Running dependency scans..."
            # Add dependency scanners here
          fi
          
          # BPF Scans
          if [ "${{ env.ENABLE_BPF_CHECKS }}" = "true" ]; then
            echo "Running BPF security checks..."
            # Add BPF security checks here
          fi
          
          # Container Scans
          if [ "${{ env.ENABLE_CONTAINER_SCAN }}" = "true" ]; then
            echo "Running container security scans..."
            # Add container security scans here
          fi
          
          # Secret Scans
          if [ "${{ env.ENABLE_SECRET_SCANNING }}" = "true" ]; then
            echo "Running secret scans..."
            # Add secret scanning tools here
          fi
          
          # Wait for all background processes to complete
          wait
        )
    
    # Process and report results
    - name: Process Results
      if: always()
      run: |
        # Process scan results and generate reports
        echo "Processing scan results..."
        
        # Generate summary report
        echo "# Security Scan Summary" > ./results/reports/security-summary.md
        echo "## Scan ID: ${{ env.SCAN_ID }}" >> ./results/reports/security-summary.md
        echo "## Completed: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> ./results/reports/security-summary.md
        echo "## Repository: $GITHUB_REPOSITORY" >> ./results/reports/security-summary.md
        echo "## Branch: $GITHUB_REF_NAME" >> ./results/reports/security-summary.md
        echo "## Commit: $GITHUB_SHA" >> ./results/reports/security-summary.md
        
        # Add scan results to the summary
        echo -e "\n## Scan Results" >> ./results/reports/security-summary.md
        
        # Determine overall status
        if [ -f "./results/failure.flag" ]; then
          echo "❌ **Security scan completed with failures**" >> ./results/reports/security-summary.md
          echo "::set-output name=scan_status::failure"
        else
          echo "✅ **All security checks passed**" >> ./results/reports/security-summary.md
          echo "::set-output name=scan_status::success"
        fi
        
        # Generate SARIF report if needed
        # ...
        
        # Generate SBOM if enabled
        if [ "${{ env.ENABLE_SBOM_GENERATION }}" = "true" ]; then
          echo "Generating SBOM..."
          # Add SBOM generation commands here
        fi
    
    # Upload artifacts
    - name: Upload Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: security-scan-results
        path: |
          ./results/**/*
          !./results/tmp/**
        retention-days: 7
        if-no-files-found: warn
    
    # Upload SARIF results for GitHub code scanning
    - name: Upload SARIF Results
      if: always() && github.event_name != 'schedule'
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ./results/reports/security-scan-results.sarif
        check_name: Advanced Security Scan
    
    # Security Gate
    - name: Security Gate
      if: steps.process_results.outputs.scan_status == 'failure' && github.event_name == 'pull_request'
      run: |
        echo "::error::Security gate failed. Please review the security scan results."
        exit 1
    
    # Notifications
    - name: Send Notification
      if: always() && env.NOTIFY_ON != 'never' && (env.NOTIFY_ON == 'always' || steps.process_results.outputs.scan_status == 'failure')
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ steps.process_results.outputs.scan_status == 'success' && '#36a64f' || '#ff0000' }}
        SLACK_TITLE: "Security Scan ${{ steps.process_results.outputs.scan_status == 'success' && 'Passed' : 'Failed' }} - ${{ github.repository }}"
        SLACK_MESSAGE: |
          *Repository*: ${{ github.repository }}
          *Branch*: ${{ github.ref_name }}
          *Commit*: <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${GITHUB_SHA:0:8}>
          *Workflow*: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>
          *Status*: ${{ steps.process_results.outputs.scan_status == 'success' && '✅ All checks passed' : '❌ Some checks failed' }}
          
          View the full report in the workflow artifacts.
        MSG_MINIMAL: false
        SLACK_FOOTER: "Scan ID: ${{ env.SCAN_ID }} | Completed at $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
